# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 40, 691, 671))
        self.widget.setObjectName("widget")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 691, 671))
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_11.setMouseTracking(True)
        self.label_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(820, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(730, 40, 376, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(730, 80, 116, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(860, 80, 116, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(990, 80, 116, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(730, 160, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.horizontalSlider = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(22, 27, 160, 22))
        self.horizontalSlider.setMinimum(-100)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(75, 2, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(51, 105, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(76, 55, 51, 29))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_2.setGeometry(QtCore.QRect(76, 157, 51, 29))
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(22, 129, 160, 22))
        self.horizontalSlider_2.setMinimum(-100)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(0, 46, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(0, 147, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(183, 46, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(183, 147, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_11.setGeometry(QtCore.QRect(108, 210, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_18.setGeometry(QtCore.QRect(28, 210, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(730, 460, 201, 151))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_12.setGeometry(QtCore.QRect(22, 16, 161, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_13.setGeometry(QtCore.QRect(22, 61, 161, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_14.setGeometry(QtCore.QRect(22, 106, 161, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(970, 150, 137, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(8, 10, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(8, 55, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(8, 100, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(8, 235, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(8, 145, 121, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(8, 190, 121, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(8, 280, 121, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(8, 325, 121, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(8, 370, 121, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(744, 135, 141, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(744, 435, 141, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(730, 650, 116, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(860, 650, 116, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(990, 650, 116, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(710, 445, 20, 181))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(720, 438, 21, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(800, 438, 142, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(935, 445, 16, 181))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(720, 618, 222, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(710, 144, 20, 270))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(720, 144, 20, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(877, 137, 63, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(930, 144, 20, 270))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(719, 407, 221, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(960, 618, 155, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(982, 135, 61, 16))
        self.label_10.setObjectName("label_10")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(959, 144, 20, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(950, 145, 20, 481))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(1106, 144, 20, 482))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(1031, 137, 85, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 10, 21, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(50, 10, 21, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_6 = QtWidgets.QMenu(self.menu_3)
        self.menu_6.setObjectName("menu_6")
        self.menu_4 = QtWidgets.QMenu(self.menu_3)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_17 = QtWidgets.QAction(MainWindow)
        self.action_17.setObjectName("action_17")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.action_19 = QtWidgets.QAction(MainWindow)
        self.action_19.setObjectName("action_19")
        self.action_24 = QtWidgets.QAction(MainWindow)
        self.action_24.setObjectName("action_24")
        self.action_25 = QtWidgets.QAction(MainWindow)
        self.action_25.setObjectName("action_25")
        self.action180 = QtWidgets.QAction(MainWindow)
        self.action180.setObjectName("action180")
        self.action90 = QtWidgets.QAction(MainWindow)
        self.action90.setObjectName("action90")
        self.action90_2 = QtWidgets.QAction(MainWindow)
        self.action90_2.setObjectName("action90_2")
        self.action_26 = QtWidgets.QAction(MainWindow)
        self.action_26.setObjectName("action_26")
        self.action_27 = QtWidgets.QAction(MainWindow)
        self.action_27.setObjectName("action_27")
        self.action_28 = QtWidgets.QAction(MainWindow)
        self.action_28.setObjectName("action_28")
        self.action_29 = QtWidgets.QAction(MainWindow)
        self.action_29.setObjectName("action_29")
        self.action_30 = QtWidgets.QAction(MainWindow)
        self.action_30.setObjectName("action_30")
        self.action_31 = QtWidgets.QAction(MainWindow)
        self.action_31.setObjectName("action_31")
        self.action_32 = QtWidgets.QAction(MainWindow)
        self.action_32.setObjectName("action_32")
        self.action_33 = QtWidgets.QAction(MainWindow)
        self.action_33.setObjectName("action_33")
        self.action_34 = QtWidgets.QAction(MainWindow)
        self.action_34.setObjectName("action_34")
        self.action_35 = QtWidgets.QAction(MainWindow)
        self.action_35.setObjectName("action_35")
        self.menu.addAction(self.action_6)
        self.menu.addAction(self.action_9)
        self.menu.addAction(self.action_10)
        self.menu.addSeparator()
        self.menu.addAction(self.action_12)
        self.menu_2.addAction(self.action_13)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_15)
        self.menu_6.addAction(self.action_26)
        self.menu_6.addAction(self.action_27)
        self.menu_6.addAction(self.action_28)
        self.menu_6.addAction(self.action_29)
        self.menu_6.addAction(self.action_30)
        self.menu_6.addAction(self.action_31)
        self.menu_6.addAction(self.action_32)
        self.menu_6.addAction(self.action_33)
        self.menu_6.addAction(self.action_34)
        self.menu_4.addAction(self.action_24)
        self.menu_4.addAction(self.action_25)
        self.menu_5.addAction(self.action180)
        self.menu_5.addAction(self.action90)
        self.menu_5.addAction(self.action90_2)
        self.menu_3.addAction(self.action_17)
        self.menu_3.addAction(self.action_18)
        self.menu_3.addAction(self.action_19)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.menu_6.menuAction())
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_3.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Информация о файле:"))
        self.label_2.setText(_translate("MainWindow", "Яркость"))
        self.label_3.setText(_translate("MainWindow", "Контрастность"))
        self.label_4.setText(_translate("MainWindow", "-100"))
        self.label_5.setText(_translate("MainWindow", "-100"))
        self.label_6.setText(_translate("MainWindow", "100"))
        self.label_7.setText(_translate("MainWindow", "100"))
        self.pushButton_11.setText(_translate("MainWindow", "Сбросить"))
        self.pushButton_18.setText(_translate("MainWindow", "Применить"))
        self.pushButton_12.setText(_translate("MainWindow", "Автояркость"))
        self.pushButton_13.setText(_translate("MainWindow", "Автоконтрастность"))
        self.pushButton_14.setText(_translate("MainWindow", "Авто - цветокоррекция"))
        self.pushButton.setText(_translate("MainWindow", "Черно-белый"))
        self.pushButton_2.setText(_translate("MainWindow", "Размытие"))
        self.pushButton_3.setText(_translate("MainWindow", "Обесцветить"))
        self.pushButton_4.setText(_translate("MainWindow", "Негатив"))
        self.pushButton_5.setText(_translate("MainWindow", "Сепия"))
        self.pushButton_6.setText(_translate("MainWindow", "Псевдоцвет"))
        self.pushButton_7.setText(_translate("MainWindow", "Оттенки красного"))
        self.pushButton_8.setText(_translate("MainWindow", "Оттенки зеленого"))
        self.pushButton_9.setText(_translate("MainWindow", "Оттенки синего"))
        self.label_8.setText(_translate("MainWindow", "Яркость и контрастность"))
        self.label_9.setText(_translate("MainWindow", "Коррекция"))
        self.pushButton_15.setText(_translate("MainWindow", "Показать оригинал"))
        self.pushButton_16.setText(_translate("MainWindow", "Сбросить"))
        self.pushButton_17.setText(_translate("MainWindow", "Очистить"))
        self.label_10.setText(_translate("MainWindow", "Фильтры"))
        self.pushButton_10.setText(_translate("MainWindow", "+"))
        self.pushButton_19.setText(_translate("MainWindow", "-"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Редактирование"))
        self.menu_3.setTitle(_translate("MainWindow", "Изображение"))
        self.menu_6.setTitle(_translate("MainWindow", "Фильтры"))
        self.menu_4.setTitle(_translate("MainWindow", "Отразить"))
        self.menu_5.setTitle(_translate("MainWindow", "Вращение"))
        self.action_6.setText(_translate("MainWindow", "Открыть"))
        self.action_9.setText(_translate("MainWindow", "Сохранить"))
        self.action_10.setText(_translate("MainWindow", "Сохранить как"))
        self.action_12.setText(_translate("MainWindow", "Выход"))
        self.action_13.setText(_translate("MainWindow", "Сбросить"))
        self.action_15.setText(_translate("MainWindow", "Очистить"))
        self.action_17.setText(_translate("MainWindow", "Автояркость"))
        self.action_18.setText(_translate("MainWindow", "Автоконстраст"))
        self.action_19.setText(_translate("MainWindow", "Автоматическая цветокоррекция"))
        self.action_24.setText(_translate("MainWindow", "По вертикали"))
        self.action_25.setText(_translate("MainWindow", "По горизонтали"))
        self.action180.setText(_translate("MainWindow", "180°"))
        self.action90.setText(_translate("MainWindow", "90° по часовой ⤾"))
        self.action90_2.setText(_translate("MainWindow", "90° против часовой ⤿"))
        self.action_26.setText(_translate("MainWindow", "Черно-белый"))
        self.action_27.setText(_translate("MainWindow", "Размытие"))
        self.action_28.setText(_translate("MainWindow", "Обесцветить"))
        self.action_29.setText(_translate("MainWindow", "Сепия"))
        self.action_30.setText(_translate("MainWindow", "Псевдоцвет"))
        self.action_31.setText(_translate("MainWindow", "Негатив"))
        self.action_32.setText(_translate("MainWindow", "Оттенки красного"))
        self.action_33.setText(_translate("MainWindow", "Оттенки зеленого"))
        self.action_34.setText(_translate("MainWindow", "Оттенки синего"))
        self.action_35.setText(_translate("MainWindow", "Раскраска"))
